making sure db is ready in test environment of Github Actions

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -68,12 +68,21 @@ jobs:
       - name: Run api
         run: |
           docker network ls | grep minitwit-network || docker network create minitwit-network
-          docker build -t db -f ./database/Dockerfile .
+          docker build -t database -f ./database/Dockerfile .
           docker run -d --name db --network minitwit-network -p 5432:5432 db
           sleep 10
           docker compose up -d
+          max_attempts=5
+          attempts=0
           until curl -s http://localhost:5000/health > /dev/null; do
             docker logs minitwit-api-instance
+          echo "Attempt $attempts of $max_attempts failed, checking again in 1 second..."
+          
+          if [ "$attempts" -ge "$max_attempts" ]; then
+            echo "Service did not become available after $max_attempts attempts, exiting."
+            docker logs minitwit-api-instance
+            exit 1
+          fi
             sleep 1
           done
           cd api
